### ISSUE TITLE
Why TimeDistributed layer before attention layer?

### ISSUE THREAD

**Issue by hdchao1989** [richliao/textClassifier#3]
In  HATT model, TimeDistributed layer has been adopted before both word-level and sentence-level attention layer. I'm confused what does TimeDistributed layer do in here? And in RNN model, there is no TimeDistributed layer before attention layer. What's the difference? Thank U!

**Comment by richliao** [comment]
Read the paper. There's a dense layer that sit on top of RNN, which tries to combine another dimension information from RNN. Honestly I don't know if it's useful. I bet you won't see performance decrease by reducing this step.

**Comment by hdchao1989** [comment]
I see, thx~
